Разметка первой страницы
htmlacademy-htmlcss/2069427-sedona-34 pull request #2
Opened 2022-05-21 16:00 UTC by AlinaBale

2022-05-23 18:50 UTC, Zakamsky requested changes
Старательно и добротное исполнение, только пожалуйста наведи порядок в коде.
Есть еще один небольшой нюанс: 
Секции должны иметь заголовок, если у нас нет заголовка в макете, нам предстоит решить либо добавить скрытый заголовок самим, либо не использовать секцию. В целом секции с заголовком помогают разбить контент на логические части, так его проще понимать пользователю и индексировать поисковым роботам. У нас есть пара секций потерявших свои заголовки, если не найдешь их глазами - используй валидатор, он прямо подскажет на какой строке их искать.

2022-05-23 18:50 UTC, Zakamsky commented on index.html
> +<p><b>Седона — небольшой городок в Аризоне,заслуживающий большего!</b></p>
Я бы избегал использования оформительских тэгов. Если это текст выделен по смыслу, надо использовать семантическое выделение тэгом. если это просто жирный текст - лучше задать параграфу класс и сделать текст жирным стилями.

2022-05-23 18:50 UTC, Zakamsky commented on index.html
> +            <br>Да, по нему можно пройти! Если вы осмелитесь, разумеется
а точно у нас все эти тэга вложены друг в друга? 
Выровняй пожалуйста код, его очень сложно читать. 
Кроме того это нарушает критерий [PROJ-01.](https://up.htmlacademy.ru/htmlcss/34/criteries#PROJ-01) (это важно так как на порядок в коде смотрят при приеме на работу.)
Я понимаю что ты можешь не защищаться, но я бы советовал привыкать делать все красиво. Самой же потом удобнее будет.

2022-05-23 18:50 UTC, Zakamsky commented on index.html
> +                <br> Все достопримечательности находятся очень близко
А что это конструкция?
кажется это совсем не часть контента, давай ее уберем и добавим позже из стилей.
(я про черточки, номер и `br`)

2022-05-23 18:50 UTC, Zakamsky commented on index.html
> +<h1 class="section-title">Заинтересовались?</h1>
тут у нас сразу две проблемы:
1. `<h1>` может быть только один на странице, это заголовок страницы
2. он не может быть внутри секции, т.к. он становится заголовком секции, а не страницы.
решение очень простое - т.к. у нас уже есть корректный `<h1>` выше давай просто замени его на `<h2>` (обрати внимание что подзаголовки тоже надо поменять на один уровень ниже)

В остальном у тебя структура заголовков хорошая.

2022-05-25 18:02 UTC, AlinaBale reviewed
Исправила ошибки в первой странице (index.html)
По каталогу были вопросы. В теории этого не рассматривают, но все же, какой тег использовать для ячеек диапазона цен и "ползунка" и как лучше это разметить?

2022-05-30 10:58 UTC, Zakamsky approved these changes
> По каталогу были вопросы. ... какой тег использовать для ячеек диапазона цен и "ползунка" и как лучше это разметить?

Это говорили в разборе, но видимо невнятно, т.к. мы обсуждали этот момент в чате (поглядывай туда пожалуйста) - пока оставь этот элемент, у нас будет демка и ее разбор, как и почему именно так сделать этот диапазон.

Работа над ошибками сделана на отлично, Картинки тоже добавлены корректно и в нужном формате. Все нужное на месте и ничего лишнего.

2022-05-30 10:58 UTC, merged